### ISSUE TITLE
Original timestamp of tweet not used while importing from Twitter archive

### ISSUE THREAD

**Issue by nazimul-haque** [robertoszek/pleroma-bot#123]
Hi, it's a very useful repository, no doubt.
What to do if I wish to record the original tweet timestamp in place of import time which is shown in Pleroma timeline while importing tweets from a Twitter archive?

**Comment by robertoszek** [comment]
Hi!
Have you tried using [`original_date`](https://robertoszek.github.io/pleroma-bot/gettingstarted/configuration/#mappings) on your config already?
Something along the lines of this:
```yaml
pleroma_base_url: https://pleroma.instance
users:
- twitter_username: User1
  pleroma_username: MyPleromaUser1
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  archive: /path/to/archive.zip
  original_date: true # <--
```

This will add the creation date of the original tweet to the body of the post on Pleroma:
```
New thing! Consume product!

 🐦🔗: https://nitter.net/someuser/status/1234

[2022-12-13 01:14]
```
Unfortunately neither Mastodon nor Pleroma support setting a date in the past when posting new statuses (https://github.com/mastodon/mastodon/issues/12423), so this is the best we can do from our side.


If after setting `original_date` to `true` you're still encountering issues, let me know so we can investigate further.
