### ISSUE TITLE
Enable targetting of particular tweets by ID or hashtag

### ISSUE THREAD

**Issue by lightnin** [robertoszek/pleroma-bot#40]
This project seems immensely useful for people who are transitioning from twitter to the fediverse - or want to maintain presences on both. 
I wonder if it could be adapted to enable the transfer of targeted tweets from twitter to an account on the fediverse. The use case I'm imagining is my own: I have been documenting tinkering projects with brief videos shared to twitter, most of which have the hashtag #tinkering . I would like to be able to move just those tweets and associated media over to my pleroma account, which would then be a repository of tinkering projects in the past, as well as going forward.

This seems to have nearly the functionality required to do this except it's not feasible to target tweets with particular hashtags or IDs. 
Apologies if this is out of scope. I just thought I would see if such functionality was interesting as it seems only a step or two away from the current implementation, and could be achieved by adding a check against hashtags in the tweets.
Thanks for your attention, and for sharing this tool.

**Comment by robertoszek** [comment]
Hi!
First of all, thank you for your kind words! It's certainly rewarding to hear some people get an use out of the tool I just threw together for my own needs.

I appreciate the feature request, nothing it's out of scope as far I'm concerned haha
So it basically boils down to, and feel free to correct me if I'm wrong, filtering by hashtags and/or tweet IDs.

After thinking it over a little bit, I assume you should be able to set the hashtags and/or tweet IDs for the filter both at runtime and in the config file.

I'm imagining the hastags and tweets IDs as a list (even if it's just a one item list) to be evaluated while filtering the tweets. 

In the config file, it would look like something along the lines of this:

```yaml
twitter_base_url: https://api.twitter.com/1.1
pleroma_base_url: https://pleromaormastodon.instance
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username: KyleBosman
  pleroma_username: KyleBosman
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  hashtags:
  - tinkering
  - sunsets
  - diy
  - puppies
  tweet_ids:
  - 10765432100123456789
  - 10765432100123456790
  - 10765432100123456791
```

And for setting them at runtime, maybe something like this:

```bash
pleroma-bot --hastags tinkering sunsets diy puppies --tweet_ids 10765432100123456789 10765432100123456790 10765432100123456791
```

Let me know if this is what you're looking for or if you envisioned using it some other way for your usecase.
