### ISSUE TITLE
Media gets lost if one of the attachments returns 404

### ISSUE THREAD

**Issue by Cknight70** [robertoszek/pleroma-bot#67]
When retweeting on Twitter, the post will only include the text, but not the image of the tweet. 

Tested with: 1.0.2

my config.yml
```
twitter_base_url: https://api.twitter.com/1.1
# Change this to your Fediverse instance
pleroma_base_url: https://pleroma.url
# How many tweets to get in every execution
# Twitter's API hard limit is 3,200
max_tweets: 40
# Twitter bearer token
twitter_token: xxxx
# List of users and their attributes
users:
- twitter_username: xxxx
  pleroma_username: xxxx
  # Mastodon/Pleroma token obtained by following the README.md
  pleroma_token: xxxxx
  # (optional) keys and secrets for using OAuth 1.0a (for protected accounts)
  consumer_key: xxxxx
  consumer_secret: xxxx
  access_token_key: xx-xxx
  access_token_secret: xxxx
  # If you want to add a link to the original status or not
  signature: false
  # (optional) If you want to download Twitter attachments and add them to the Pleroma posts.
  # By default they are not
  media_upload: true
  # (optional) If twitter links should be changed to nitter ones. By default they are not
  nitter: false
  # (optional) If mentions should be transformed to links to the mentioned Twitter profile
  rich_text: true
  # (optional) visibility of the post. Must one of the following: public, unlisted, private, direct
  # by default is "unlisted"
  visibility: "public"
  # (optional) Force all posts for this account to be sensitive or not
  # The NSFW banner for the instance will be shown for attachments as a warning if true
  # If not defined, the original tweet sensitivity will be used on a tweet by tweet basis
  sensitive: false
  # (optional) Include the creation date of the tweet on the Fediverse post body
  original_date: false
  # (optional) Date format to use when adding the creation date of the tweet to the Fediverse post
  original_date_format: "%Y/%m/%d %H:%"
  # (optional) If RTs are to be also be posted in the Fediverse account. By default they are included
  include_rts: true
  # (optional) If replies are to be also posted in the Fediverse account. By default they are included
  include_replies: false
   # (optional) How big attachments can be before being ignored and not being uploaded to the Fediverse post
  # Examples: "30MB", "1.5GB", "0.5TB"
  twitter_bio: false
  file_max_size: 500MB
  bio_text: "my bio text woo"
```

Retweets should include the image if media upload is true.
