### ISSUE TITLE
Allow multiple 'twitter_username' values in config

### ISSUE THREAD

**Issue by robertoszek** [robertoszek/pleroma-bot#7]
Support ‘twitter_username’ being a list of Twitter accounts to mirror and consolidate all tweets into a single Fediverse account. It'd be nice if the tweets are posted based on date, not dumped from each Twitter user one after the other.

Don’t update the Pleroma profile if 'twitter_username' is a list, I guess.

Something along the lines of this:
```yaml
users:
- twitter_username: 
  - TwitterUser1
  - TwitterUser2
  - TwitterUser3
  pleroma_username: NewsBot
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
- twitter_username: OnlyOneUser
  pleroma_username: MyUniqueAccount
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

This will necessitate the change of the behaviour of some loops or some of the User object attributes.

**Comment by robertoszek** [comment]
There have been some advancements with 2cc5a77689ef2b37c7a406e6ae15eb39d75478bd but right now tweets are not merged into a single Fedi account and thus won't be ordered by date.

**Comment by vegar-ctrl** [comment]
I would really love this feature. As it stands now the config file is long and cumbersome. In regards to adding users, I actually can't understand it.

**Comment by robertoszek** [comment]
> I would really love this feature. As it stands now the config file is long and cumbersome. In regards to adding users, I actually can't understand it.

Hi,
Would you mind elaborating on what you don't understand? I'm genuinely asking, I aim to make the config template more clear and/or the explanation in the README a bit more digestible.

Regarding the config file being long, a minimal config looks something like this:

```yaml
twitter_base_url: https://api.twitter.com/1.1
pleroma_base_url: https://pleroma.instance
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username: User1
  pleroma_username: MyPleromaUser1
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  bio_text: ""
```

Everything else is optional, "users" is a [YAML list](https://gettaurus.org/docs/YAMLTutorial/#Lists-and-Dictionaries) (hence the hyphens denoting each entry of the list) so you can add as little as 1 user and as much as you need.
