### ISSUE TITLE
Mirror Twitter profile metadata to Mastodon (like website)

### ISSUE THREAD

**Issue by nemobis** [robertoszek/pleroma-bot#81]
Most Twitter accounts (?) link a website, for instance https://nitter.eu/peterliese links https://www.peter-liese.de/ .

There is no direct mapping in Mastodon, but I usually use one of the 4 metadata slots with a label "WWW" and put the website URL there.

The website is reachable through the nitter URLs, and most pleroma-bot users create the fediverse profile manually, so the main use case is someone who's mirroring multiple profiles, wants to give attribution by link to the source and doesn't want to rely on nitter for that.

**Comment by robertoszek** [comment]
You could already update the metadata fields manually with something like this:
```
pleroma_base_url: https://pleroma.instance
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username: User1
  pleroma_username: MyPleromaUser1
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  fields:
    - name: "WWW"
      value: "https://mywebsite.com"
```

However, you would need to gather the value yourself and keep it updated in case the Twitter account changes it.

So I see the value of doing it programmatically, I've released a release candidate version (1.0.3rc11) that gathers the website from the Twitter profile and lets you use it on the config file:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.0.3rc11
```
So you could keep it up-to-date like this:
```
pleroma_base_url: https://pleroma.instance
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username: User1
  pleroma_username: MyPleromaUser1
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  fields:
    - name: "WWW"
      value: "{{ website }}"
```

`{{ website }}` will be replaced by the expanded_url value of the website listed on the Twitter's account profile.
